### PR TITLE
Re-enable windows support (Closes #13)

### LINKED ISSUE #13: Bumping R version for Rtools 3.4 to enable Windows support
With the release of R 3.3.0, the Rtools 3.4 tool chain became the standard bearer for compilation.For this release, the toolchain has been updated to use gcc 4.9.3. Per the `SystemRequirements` note, the updated version of gcc should allow for RcppMLPACK to work on Windows with only a change in R version dependency (e.g. `R (>=3.2.0)` => `R (>= 3.3.0)`). Therefore, with a slight change, the floodgate for using this package can be opened.

### PR DESCRIPTION
**Pull request by coatless**
- Bumps version dependency from R3.2 to R3.3.0 as that is the only valid version of R with an appropriate compiler for Windows. 

- Adds a configure script to validate that gcc is > 4.6.* (mirrored from RcppArmadillo as that provides support for gcc >= 4.6.*)

- Address a path spacing issue that exists due to a lack of quotations link file '"'

### CODE REVIEW

**Comment by thirdwing** [comment]
Can you fix this?

**Comment by coatless** [comment]
Aye, I can. Specifically, the issue is related to the gcc version that Travis is running being slightly lower than what the new `configure.ac` script requires.

**Comment by eddelbuettel** [comment]
There are ways around that by pointing to particular PPAs with newer versions.  Also, and maybe easiest, switching to `trusty` should help.

**Comment by eddelbuettel** [comment]
This just worked in [this new build](https://travis-ci.org/thirdwing/RcppMLPACK/builds/181326090).

I'll make a new PR.

**Comment by thirdwing** [comment]
@coatless Can you do a rebase/merge? I will merge if the travis passes.

**Comment by eddelbuettel** [comment]
I glanced at the failure report and it looked like something was up with configure.  Had no time to look.  _May_ go away given that we now tell Travis to use the newer Trusty aka 14.04.

**Comment by coatless** [comment]
@thirdwing: seems to be an issue with the configure.ac not being able to pick up a valid `gcc` on travis under the new build config. I haven't had time to investigate recently as the semester is ending.

I hope to look into this sometime next week if that is okay.

**Comment by eddelbuettel** [comment]
Hold on. I am build a bazillion packages of mine there, all the same way, and also just built the changeset I pushed to rcppmlpack2 that way.

Something smells like seafood here.  It's prolly something trivial.

Can you back out the changes and reapply them after my changes to piggy-back onto something working?

**Comment by eddelbuettel** [comment]
(And not to state the obvious, we never run `configure.ac`.  We call `autoconf` to produce `configure` from it.  There were changes with `autoconf` at points in the past but it _should_ be fine now.  But of course I don't know what the world looks like over where you cool kids on your shiny OS X machines live...  Over here in the rural Finnish village things just work...)

**Comment by coatless** [comment]
Aye, looks like this PR needs to be killed and then resubmitted. 

c.f.

https://travis-ci.org/coatless/RcppMLPACK2/builds/185348219

**Comment by thirdwing** [comment]
@coatless Let's work on Dirk's repo. I probably will upload the static Windows libraries tomorrow.

Then let's make a submission to CRAN.

**Comment by eddelbuettel** [comment]
Or we morph [mine](https://github.com/eddelbuettel/rcppmlpack2)  into [yours](https://github.com/thirdwing/RcppMLPACK)?

I started with a clean fork to keep all the history, and it shouldn't really be a merge conflict.  I could just PR it over.  

Or we stick it all into the RcppCore org, or ...

Many choices. No rush.  Windows builds are most important and possibly a challenge.

(And whoever has energy left I have another (smaller) Windows puzzle with [(Rcpp)CCTZ](https://github.com/eddelbuettel/rcppcctz)...

**Comment by thirdwing** [comment]
Actually not a huge problem with the new Rtools.

I am using the same version of MinGW in the lab for Windows building, so at least I don't need to build the boost again.

**Comment by coatless** [comment]
If it's okay @thirdwing, could I just resubmit the PR to this repo?
You can then set a release on GH so that any folks who opt to _not_ use V2 at least have something to fallback to that is cross platform.

**Comment by thirdwing** [comment]
No problem. I think I already add you into the repo. You should be able to set the release.

**Pull request closed without merging**
